//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountdownDataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountdownSettings
    {
        public CountdownSettings()
        {
            this.Days = new HashSet<Days>();
            this.Weeks = new HashSet<Weeks>();
            this.Monthes = new HashSet<Monthes>();
        }
    
        public int Id { get; set; }
        public int Duration { get; set; }
        public System.DateTime Start { get; set; }
    
        public virtual Reminder Reminder { get; set; }
        public virtual ICollection<Days> Days { get; set; }
        public virtual ICollection<Weeks> Weeks { get; set; }
        public virtual ICollection<Monthes> Monthes { get; set; }
    }
}
