//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountdownDataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercises
    {
        public Exercises()
        {
            this.Files = new HashSet<Files>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReminderId { get; set; }
    
        public virtual Reminder Reminder { get; set; }
        public virtual ICollection<Files> Files { get; set; }
    }
}
