//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountdownDataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public Files()
        {
            this.Images = new HashSet<Images>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ExercisesId { get; set; }
    
        public virtual Exercises Exercis { get; set; }
        public virtual ICollection<Images> Images { get; set; }
    }
}
