//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountdownDataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public Reminder()
        {
            this.ReminderSettings = new HashSet<ReminderSettings>();
            this.Exercises = new HashSet<Exercises>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int TypeOfReminderId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<ReminderSettings> ReminderSettings { get; set; }
        public virtual ICollection<Exercises> Exercises { get; set; }
        public virtual TypeOfReminder TypeOfReminder { get; set; }
        public virtual ProgressSettings ProgressSetting { get; set; }
        public virtual CountdownSettings CountdownSetting { get; set; }
        public virtual Users User { get; set; }
    }
}
