//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountdownDataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReminderSettings
    {
        public int ReminderId { get; set; }
        public int SettingsId { get; set; }
        public string ValueSetting { get; set; }
    
        public virtual Reminder Reminder { get; set; }
        public virtual Settings Setting { get; set; }
    }
}
