//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountdownDataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public Settings()
        {
            this.ReminderSettings = new HashSet<ReminderSettings>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int TypeOfReminderId { get; set; }
        public string NameProperty { get; set; }
        public string NameElement { get; set; }
    
        public virtual ICollection<ReminderSettings> ReminderSettings { get; set; }
        public virtual TypeOfReminder TypeOfReminder { get; set; }
    }
}
