//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountdownDataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfReminder
    {
        public TypeOfReminder()
        {
            this.Reminders = new HashSet<Reminder>();
            this.Settings = new HashSet<Settings>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Reminder> Reminders { get; set; }
        public virtual ICollection<Settings> Settings { get; set; }
    }
}
